In [2]:
import pandas as pd
red_wine = pd.read_csv('data/winequality-red.csv', sep=';')
red_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
white_wine = pd.read_csv('data/winequality-white.csv', sep=';')
white_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
red_wine.insert(11, 'class', 0)
white_wine.insert(11, 'class', 1)

In [5]:
wine_df = pd.concat([red_wine, white_wine], ignore_index=True)
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,class,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,0,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,0,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,0,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,0,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,1,6
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,1,5
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,1,6
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,1,7
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,1,6

In [6]:
from sklearn.preprocessing import MinMaxScaler

mm_scaler = MinMaxScaler()
wine_df[['fixed acidity', 'residual sugar', 'free sulfur dioxide', 
         'total sulfur dioxide', 'pH', 'alcohol']] = \
mm_scaler.fit_transform(wine_df[['fixed acidity', 'residual sugar', 
                                 'free sulfur dioxide', 
                                 'total sulfur dioxide', 'pH', 'alcohol']])
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,class,quality
0,0.297521,0.70,0.00,0.019939,0.076,0.034722,0.064516,0.99780,0.612403,0.56,0.202899,0,5
1,0.330579,0.88,0.00,0.030675,0.098,0.083333,0.140553,0.99680,0.372093,0.68,0.260870,0,5
2,0.330579,0.76,0.04,0.026074,0.092,0.048611,0.110599,0.99700,0.418605,0.65,0.260870,0,5
3,0.611570,0.28,0.56,0.019939,0.075,0.055556,0.124424,0.99800,0.341085,0.58,0.260870,0,6
4,0.297521,0.70,0.00,0.019939,0.076,0.034722,0.064516,0.99780,0.612403,0.56,0.202899,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,0.198347,0.21,0.29,0.015337,0.039,0.079861,0.198157,0.99114,0.426357,0.50,0.463768,1,6
6493,0.231405,0.32,0.36,0.113497,0.047,0.194444,0.373272,0.99490,0.333333,0.46,0.231884,1,5
6494,0.223140,0.24,0.19,0.009202,0.041,0.100694,0.241935,0.99254,0.209302,0.46,0.202899,1,6
6495,0.140496,0.29,0.30,0.007669,0.022,0.065972,0.239631,0.98869,0.480620,0.38,0.695652,1,7
6496,0.181818,0.21,0.38,0.003067,0.020,0.072917,0.211982,0.98941,0.418605,0.32,0.550725,1,6

In [7]:
X = wine_df.iloc[:, :12]
y = wine_df.iloc[:, 12].values

In [8]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, 11)
y.shape

(6497, 11)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True)

In [10]:
from tensorflow.keras import models, layers, optimizers

model = models.Sequential()
model.add(layers.Dense(24, input_dim=12, activation='relu'))
model.add(layers.Dense(24, activation='relu'))
model.add(layers.Dense(11, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 24)                312

 dense_1 (Dense)             (None, 24)                600

 dense_2 (Dense)             (None, 11)                275

=================================================================
Total params: 1,187
Trainable params: 1,187
Non-trainable params: 0
_________________________________________________________________

In [11]:
model.compile(loss='categorical_crossentropy', optimizer=optimizers.Adam(learning_rate=0.05), #learning rate 0.05
              metrics=['accuracy'])
h = model.fit(X_train, y_train, epochs=60, batch_size=300)

Epoch 1/60
17/17 [==============================] - 1s 1ms/step - loss: 1.3970 - accuracy: 0.4477
Epoch 2/60
17/17 [==============================] - 0s 2ms/step - loss: 1.1524 - accuracy: 0.5123
Epoch 3/60
17/17 [==============================] - 0s 1ms/step - loss: 1.1331 - accuracy: 0.5127
Epoch 4/60
17/17 [==============================] - 0s 1ms/step - loss: 1.1053 - accuracy: 0.5246
Epoch 5/60
17/17 [==============================] - 0s 1ms/step - loss: 1.1066 - accuracy: 0.5263
Epoch 6/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0950 - accuracy: 0.5328
Epoch 7/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0892 - accuracy: 0.5333
Epoch 8/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0929 - accuracy: 0.5345
Epoch 9/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0827 - accuracy: 0.5376
Epoch 10/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0810 - accuracy: 0.5421
Epoch 11/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0802 - accuracy: 0.5359
Epoch 12/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0793 - accuracy: 0.5359
Epoch 13/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0676 - accuracy: 0.5429
Epoch 14/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0672 - accuracy: 0.5421
Epoch 15/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0677 - accuracy: 0.5491
Epoch 16/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0584 - accuracy: 0.5530
Epoch 17/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0702 - accuracy: 0.5408
Epoch 18/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0623 - accuracy: 0.5460
Epoch 19/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0554 - accuracy: 0.5489
Epoch 20/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0588 - accuracy: 0.5441
Epoch 21/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0529 - accuracy: 0.5534
Epoch 22/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0626 - accuracy: 0.5429
Epoch 23/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0523 - accuracy: 0.5464
Epoch 24/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0460 - accuracy: 0.5511
Epoch 25/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0591 - accuracy: 0.5447
Epoch 26/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0775 - accuracy: 0.5335
Epoch 27/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0479 - accuracy: 0.5505
Epoch 28/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0474 - accuracy: 0.5466
Epoch 29/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0414 - accuracy: 0.5511
Epoch 30/60
17/17 [==============================] - 0s 2ms/step - loss: 1.0463 - accuracy: 0.5450
Epoch 31/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0443 - accuracy: 0.5501
Epoch 32/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0459 - accuracy: 0.5466
Epoch 33/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0628 - accuracy: 0.5361
Epoch 34/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0436 - accuracy: 0.5562
Epoch 35/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0369 - accuracy: 0.5517
Epoch 36/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0389 - accuracy: 0.5534
Epoch 37/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0559 - accuracy: 0.5433
Epoch 38/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0420 - accuracy: 0.5546
Epoch 39/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0490 - accuracy: 0.5456
Epoch 40/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0557 - accuracy: 0.5427
Epoch 41/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0526 - accuracy: 0.5361
Epoch 42/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0420 - accuracy: 0.5460
Epoch 43/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0364 - accuracy: 0.5482
Epoch 44/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0458 - accuracy: 0.5482
Epoch 45/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0351 - accuracy: 0.5515
Epoch 46/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0498 - accuracy: 0.5427
Epoch 47/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0316 - accuracy: 0.5503
Epoch 48/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0399 - accuracy: 0.5519
Epoch 49/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0359 - accuracy: 0.5525
Epoch 50/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0392 - accuracy: 0.5536
Epoch 51/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0447 - accuracy: 0.5509
Epoch 52/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0503 - accuracy: 0.5458
Epoch 53/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0595 - accuracy: 0.5355
Epoch 54/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0472 - accuracy: 0.5433
Epoch 55/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0437 - accuracy: 0.5519
Epoch 56/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0301 - accuracy: 0.5544
Epoch 57/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0352 - accuracy: 0.5450
Epoch 58/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0292 - accuracy: 0.5542
Epoch 59/60
17/17 [==============================] - 0s 2ms/step - loss: 1.0306 - accuracy: 0.5505
Epoch 60/60
17/17 [==============================] - 0s 1ms/step - loss: 1.0318 - accuracy: 0.5523

In [12]:
score = model.evaluate(X_test, y_test)
print('Test Accuracy:%.4f'% (score[1]))

51/51 [==============================] - 0s 918us/step - loss: 1.0300 - accuracy: 0.5729
Test Accuracy:0.5729